### ISSUE TITLE
Bytes error in `get_condor_version()`

### ISSUE THREAD

**Issue by GregoryAshton** [jrbourbeau/pycondor#117]
#### Description

When building a dag with the `submit=True` flag, I get the following error

```python
Traceback (most recent call last):
  File "/home/gregory.ashton/anaconda3/bin/bilby_pipe", line 11, in <module>
    load_entry_point('bilby-pipe', 'console_scripts', 'bilby_pipe')()
  File "/home/gregory.ashton/bilby_pipe/bilby_pipe/main.py", line 370, in main
    dag = Dag(inputs)
  File "/home/gregory.ashton/bilby_pipe/bilby_pipe/main.py", line 215, in __init__
    self.build_submit()
  File "/home/gregory.ashton/bilby_pipe/bilby_pipe/main.py", line 319, in build_submit
    self.dag.build_submit()
  File "/home/gregory.ashton/pycondor/pycondor/utils.py", line 133, in wrapper
    return func(*args, **kwargs)
  File "/home/gregory.ashton/pycondor/pycondor/dagman.py", line 412, in build_submit
    self.submit_dag(submit_options=submit_options)
  File "/home/gregory.ashton/pycondor/pycondor/utils.py", line 133, in wrapper
    return func(*args, **kwargs)
  File "/home/gregory.ashton/pycondor/pycondor/dagman.py", line 368, in submit_dag
    condor_version = get_condor_version()
  File "/home/gregory.ashton/pycondor/pycondor/utils.py", line 161, in get_condor_version
    condor_info_str).group(1)
  File "/home/gregory.ashton/anaconda3/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

This is caused by `subprocess.Popen` returning a bytes array. 

#### Suggested solution

Adding the following before the `re.search` resolves the issue. I haven't added a PR as it is pretty minor. I think this should be safe across python 2 as well.

```
try:                                                                        
    condor_info_str = condor_info_str.decode('utf-8')                       
except AttributeError:                                                      
    pass
```

#### Extra info
Issue found on 
Python version: 3.6 (anaconda-installed)
CondorVersion: 8.6.12 Jul 31 2018 BuildID: 446077
CondorPlatform: x86_64_RedHat7

**Comment by jrbourbeau** [comment]
Thanks for the bug report and solution @GregoryAshton! I'm able to reproduce this issue and am working on a fix over in #119.
